name: My JavaScript Action Test
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Run the local action in ./joke-action
      - uses: ./joke-action
